In [15]:
import numpy as np
import pandas as pd
lables = ['a', 'b', 'c']
l = [1,2,3]
arr = np.array(l)
d = {'1':10, '2':20, '3':30}
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [21]:
data = {
    'name' : ['dhvani','mit','raj'],
    'age' : [20,32,25],
    'city' : ['surat','ahmedabad','vadodara']
}
df =pd.DataFrame(data)
df

     name  age       city
0  dhvani   20      surat
1     mit   32  ahmedabad
2     raj   25   vadodara

In [ ]:
data_list =[
['julia', 34,'new york'],
['dhanu' , 24,'rjk']
]
pd.DataFrame(data_list,index=['0','1'],columns=['name','age','city'])

    name  age      city
0  julia   34  new york
1  julia   34  new york

In [ ]:
#get specific col
df['name']

0    dhvani
1       mit
2       raj
Name: name, dtype: str

In [ ]:
#add column
df['salary'] =[10000,20000,30000]
df

     name  age       city  salary
0  dhvani   20      surat   10000
1     mit   32  ahmedabad   20000
2     raj   25   vadodara   30000

In [ ]:
#delete col
del df['salary']
df

     name  age       city
0  dhvani   20      surat
1     mit   32  ahmedabad
2     raj   25   vadodara

In [32]:
df['country'] = ['india','india','india']
df

     name  age       city country
0  dhvani   20      surat   india
1     mit   32  ahmedabad   india
2     raj   25   vadodara   india

In [ ]:

df['country'] = ['india','india','india']
df

     name  age       city country
0  dhvani   20      surat   india
1     mit   32  ahmedabad   india
2     raj   25   vadodara   india

In [ ]:
#deete col using drop
df.drop('country',axis=1,inplace=True)

In [37]:
df

     name  age       city
0  dhvani   20      surat
1     mit   32  ahmedabad
2     raj   25   vadodara

In [38]:
#selecting a row
df.loc[[0,1]]

     name  age       city
0  dhvani   20      surat
1     mit   32  ahmedabad

In [40]:
#selecting a subset of rows and col
df.loc[[1,2],['name','city']]

  name       city
1  mit  ahmedabad
2  raj   vadodara

In [ ]:
df['salary'] =[10000,20000,30000]
df

     name  age       city  salary
0  dhvani   20      surat   10000
1     mit   32  ahmedabad   20000
2     raj   25   vadodara   30000

In [52]:
df[df['age']> 22]
df[(df['age'] > 22) & (df['city'] == 'vadodara')]

  name  age      city  salary
2  raj   25  vadodara   30000

In [ ]:
#missing data
data2 = {
    'A' :[1,2,3,np.nan,5,6],
    'B':[1,2,np.nan,4,5,np.nan],
    'C':[np.nan,2,3,np.nan,5,6],
    'D':[1,np.nan,3,4,5,6],
}
df2 = pd.DataFrame(data2)
df2
df2.isna()
df2.isna().sum()  # to finding total num of missing value
df2.isna().any() # check if any col has mising value
df2.dropna()  #drop all rows with missing value
df2

     A    B    C    D
0  1.0  1.0  NaN  1.0
1  2.0  2.0  2.0  NaN
2  3.0  NaN  3.0  3.0
3  NaN  4.0  NaN  4.0
4  5.0  5.0  5.0  5.0
5  6.0  NaN  6.0  6.0

In [72]:
df2.dropna(thresh=3)

     A    B    C    D
0  1.0  1.0  NaN  1.0
1  2.0  2.0  2.0  NaN
2  3.0  NaN  3.0  3.0
4  5.0  5.0  5.0  5.0
5  6.0  NaN  6.0  6.0

In [76]:
df2
df2.fillna(0)

     A    B    C    D
0  1.0  1.0  0.0  1.0
1  2.0  2.0  2.0  0.0
2  3.0  0.0  3.0  3.0
3  0.0  4.0  0.0  4.0
4  5.0  5.0  5.0  5.0
5  6.0  0.0  6.0  6.0

In [77]:
values = {'A' : 100,'B': 200,'C':300,'D':400}
df2.fillna(value = values)

       A      B      C      D
0    1.0    1.0  300.0    1.0
1    2.0    2.0    2.0  400.0
2    3.0  200.0    3.0    3.0
3  100.0    4.0  300.0    4.0
4    5.0    5.0    5.0    5.0
5    6.0  200.0    6.0    6.0

In [85]:
# merging two dataframes

employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4,7],
    'name': ['Alice', 'Bob', 'Charlie', 'David','eve'],
    'department': ['HR', 'IT', 'Finance', 'Marketing','Sales']
})

departments = pd.DataFrame({
    'emp_id': [1, 2, 3, 4,5,6],
    'dept_name': ['Human Resources', 'Information Technology', 'Finance', 'Marketing','Sales','BDE']
})

In [86]:
employees

   emp_id     name department
0       1    Alice         HR
1       2      Bob         IT
2       3  Charlie    Finance
3       4    David  Marketing
4       7      eve      Sales

In [87]:
departments

   emp_id               dept_name
0       1         Human Resources
1       2  Information Technology
2       3                 Finance
3       4               Marketing
4       5                   Sales
5       6                     BDE

In [89]:
pd.merge(employees,departments)

   emp_id     name department               dept_name
0       1    Alice         HR         Human Resources
1       2      Bob         IT  Information Technology
2       3  Charlie    Finance                 Finance
3       4    David  Marketing               Marketing

In [92]:
pd.merge(employees,departments,on="emp_id",how= 'inner')

   emp_id     name department               dept_name
0       1    Alice         HR         Human Resources
1       2      Bob         IT  Information Technology
2       3  Charlie    Finance                 Finance
3       4    David  Marketing               Marketing

In [93]:
pd.merge(employees,departments,on="emp_id",how= 'outer')

   emp_id     name department               dept_name
0       1    Alice         HR         Human Resources
1       2      Bob         IT  Information Technology
2       3  Charlie    Finance                 Finance
3       4    David  Marketing               Marketing
4       5      NaN        NaN                   Sales
5       6      NaN        NaN                     BDE
6       7      eve      Sales                     NaN

In [94]:
pd.merge(employees,departments,on="emp_id",how= 'left')

   emp_id     name department               dept_name
0       1    Alice         HR         Human Resources
1       2      Bob         IT  Information Technology
2       3  Charlie    Finance                 Finance
3       4    David  Marketing               Marketing
4       7      eve      Sales                     NaN

In [95]:
pd.merge(employees,departments,on="emp_id",how= 'right')

   emp_id     name department               dept_name
0       1    Alice         HR         Human Resources
1       2      Bob         IT  Information Technology
2       3  Charlie    Finance                 Finance
3       4    David  Marketing               Marketing
4       5      NaN        NaN                   Sales
5       6      NaN        NaN                     BDE

In [ ]:
DF1 = pd.DataFrame({
    'A' : ['A0','A1','A2','A3'],
    'B' : ['B0','B1','B2','B3'],
    'C' : ['C0','C1','C2','C3'],
})
DF2= pd.DataFrame({
    'A' : ['A4','A5','A6','A7'],
    'B' : ['B4','B5','B6','B7'],
    'C' : ['C4','C5','C6','C7'],
})

In [97]:
DF1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [98]:
DF2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [99]:
pd.concat([DF1,DF2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [100]:
pd.concat([DF1,DF2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A4  B4  C4
1  A1  B1  C1  A5  B5  C5
2  A2  B2  C2  A6  B6  C6
3  A3  B3  C3  A7  B7  C7

In [101]:
df1 = pd.DataFrame({
    'A' : [1,2,3,4,5],
    'B' : [10,20,30,40,50],
    'C' : [100,200,300,400,500],
})

In [102]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [104]:
df1.shape

(5, 3)

In [105]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [106]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [107]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000